version: 0.2

env:
  variables:
    HUGO_VERSION: "0.123.0" 

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing Hugo...
      - cd /tmp
      - wget https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
      - tar -xzf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
      - mv hugo /usr/bin/hugo
      - cd $CODEBUILD_SRC_DIR
  build:
    commands:
      - echo Building site...
      - rm -rf public
      - hugo
  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync public/ s3://dukefeb1 --delete
      - echo "Build and deploy complete on $(date)"

artifacts:
  files:
    - '**/*'
